### ISSUE TITLE
if 单行的书写形式

### ISSUE THREAD

**Issue by zhanglun** [mdfe/style-guide#1]
如果if内容只要一行代码

是这种呢？

**1**

``` js
if (a==0) { alert(1); }
```

还是这种呢
**2**

``` js
if (a==0) {
  alert(1);
}
```

如果是第一种的话，那后面的 `else` 怎么接

**Comment by ipy** [comment]
都可以，不过应该是 `if(a === 0)` :laughing: 
第一种的 `else` 写在第二行跟 `if` 对齐就可以
建议如果 `else` 需要换行的话，`if` 也不要写在一行，保持统一
